### ISSUE TITLE
Building XZ for some Windows with MSYS2

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/xz-feedstock#14]
Was curious if we could look into building XZ with MSYS2 for support of older Windows. In particular, was wanting to use a copy of XZ with Visual Studio 2008 for use with a backports package. Another option that could be considered is running `c99-to-c89` on the codebase and then building it. Though perhaps just using MSYS2 will be easier.

**Comment by jakirkham** [comment]
@mingwandroid @msarahan, do you guys think going with MSYS2 would work here? If not, I could try to explore building it as part of the downstream package. Please let me know your thoughts.

**Comment by mingwandroid** [comment]
There's `m2w64-xz`.
