### ISSUE TITLE
archive this feedstock to prevent updates to hacked xz versions?

### ISSUE THREAD

**Issue by beckermr** [conda-forge/xz-feedstock#41]
Due to the recent xz backdoor discovery (), we need to prevent updates on this feedstock. The current latest version appears unaffected. 

Our best choice is to simply archive this feedstock for the time being. 

Our next best choice is remove any non-core devs from the feedstock and make sure everyone knows not to update. 

thoughts @conda-forge/core?

**Comment by xhochy** [comment]
We unarchived it again and #42 works on getting the latest release in, so I'm closing this again.
