### ISSUE TITLE
Question about 'xz-gpl-tools'

### ISSUE THREAD

**Issue by nicoddemus** [conda-forge/xz-feedstock#45]
### Comment:

Hello,

Thanks for maintaining the package.

One of the packages in this feedstock is named `xz-gpl-tools`, although it seems it is multi-licensed: https://github.com/conda-forge/xz-feedstock/blob/ac52d61fface9ce6cd6f9c5c410ca22ff64621b1/recipe/meta.yaml#L157-L162

We are not allowed to use GPL-licensed packages internally so the `gpl` in the name raised an internal warning here. My question is if `xz-gpl-tools` is usable in environments which cannot contain GPL-licensed packages?

**Comment by xhochy** [comment]
No, I explicitly created this package to separate the GPL-licensed tools of xz from the ones that are not GPL-licensed. As the SPDX expression says: All of the licenses apply to these tools.

> My question is if xz-gpl-tools is usable in environments which cannot contain GPL-licensed packages?

No.

**Comment by nicoddemus** [comment]
Thanks for the response!

Should the recipe be updated then to change the license for `xz-gpl-tools`?

**Comment by nicoddemus** [comment]
Also, seems like today packages depending on `xz` will also unconditionally bring `xz-gpl-tools`:

https://github.com/conda-forge/xz-feedstock/blob/ac52d61fface9ce6cd6f9c5c410ca22ff64621b1/recipe/meta.yaml#L187

Can we update the recipe to remove this? Otherwise `xz` cannot be used in environments that do not allow `gpl` packages (as it will automatically bring `xz-gpl-tools` along with it).

Happy to open a PR for it.

**Comment by nicoddemus** [comment]
Went ahead and opened https://github.com/conda-forge/xz-feedstock/pull/46 so we can move the discussion over there.

**Comment by xhochy** [comment]
If you really care about your licenses, you might want to have a look at what we (QuantCo) are doing: https://tech.quantco.com/blog/conda-deny TL;DR we run `conda-deny` in all of our CI jobs and check the license compliance of all the packages listed in the `pixi.lock` against our company-global whitelist.

**Comment by nicoddemus** [comment]
Thanks @xhochy for the suggestion, I will take a look. 👍
