### ISSUE TITLE
Something is wrong with xz 5.0.5-1 from conda-forge

### ISSUE THREAD

**Issue by 183amir** [conda-forge/xz-feedstock#7]
I am trying to release a new version of `bob.io.image` and its tests fail each time each time `xz 5.0.5-1` is used: https://travis-ci.org/conda-forge/bob.io.image-feedstock/builds/135645811
I have reported this issue here too: https://github.com/bioidiap/bob.io.image/issues/13 but I think this problem is coming from xz.
Basically the tests pass when `jpeg` and `python` and `xz` and `libtiff` are pulled from the `defaults` channel.

**Comment by ocefpaf** [comment]
@183amir I believe you already figure this out, right? Can we close this?

**Comment by 183amir** [comment]
The problem is not fixed. I just ignore that the build fails in one of the conditions: https://travis-ci.org/conda-forge/bob.io.image-feedstock/builds/138908694 This happens only on Mac.
But, it might not be a problem with `xz` after all.
